version: '3.6'
services:
  php:
    image: 'chialab/php-dev:7.4-apache'
    volumes:
      - '.:/var/www/html'
      - './docker/config/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf'